
# http://kbroman.org/minimal_make/
# http://mrbook.org/blog/tutorials/make/

all: 20180729_knaus_pinf_cnv_icpp.tex row1.tex row2.tex row3.tex
	pdflatex 20180729_knaus_pinf_cnv_icpp.tex


clean:
	rm *.aux *.log *.nav *.out *.snm *.toc

